version: "3.8"

services:
  user_service:
    build: ./user-service
    depends_on:
      - "dbuser"

  post_service:
    build: ./post-service
    depends_on:
      - "dbpost"

  apigate:
    build: ./apigate
    depends_on:
      - "redisdb"
      - "user_service"
      - "post_service"
  
  dbuser:
    image: postgres:latest
    environment:
     - POSTGRES_DATABASE=template
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1
    ports:
      - "5433:5433"
    # volumes:
      # - ./database/user.sql:docker-entrypoint-initdb.d/user.sql

  dbpost: 
    image: postgres:latest 
    environment:
     - POSTGRES_DATABASE=postdb
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1
    ports:
      - "5434:5434" 
    # volumes:
    #   - ./database/post.sql:docker-entrypoint-initdb.d/post.sql

  redisdb:
    image: redis
    ports:
      - "6378:6378"
